"use strict";
// console.log("Hello World");
let x = 10;
console.log(x);
let name1 = "absar";
console.log("My name is ", name1);
let first_name;
let last_name = "987";
first_name = "123";
console.log("🚀 ~ file: index.ts:9 ~ firs̥t_name:", first_name);
console.log(`my fiest name is${first_name} and last is${last_name} `);
